[package]
name = "lumosmark-analyzer"
version = "0.0.1"
edition = "2024"

[dependencies]
tower-lsp = "0.20.0"
tokio = { version = "1.49.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
regex = "1.12.2"
